name: Solar System Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
      
jobs:
    unit-testing:
        name: Unit-Testing
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v6
          
        - name: Setup nodeJS Version - 18
          uses: actions/setup-node@v3
          with:
            node-version: 18
            
        - name: Install Dependencies
          run: npm install
          
        - name: unit Testing
          run: npm test
          
          